#!/usr/bin/env bash
# install-app-launcher.sh - drop a double-clickable "Elite Dangerous.command"
# file into ~/Applications so you can launch without a terminal.
#
# On macOS, .command files open in Terminal and run as shell scripts. For a
# "real" .app bundle with a proper icon and Dock integration, see the
# optional app-bundle block at the bottom of this script.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"

init_logging
install_err_trap

TARGET_DIR="$HOME/Applications"
mkdir -p "$TARGET_DIR"

COMMAND_FILE="$TARGET_DIR/Elite Dangerous.command"
cat > "$COMMAND_FILE" <<EOF
#!/usr/bin/env bash
# Auto-generated by ed-mac/scripts/install-app-launcher.sh
# Wraps scripts/launch-ed.sh so double-clicking launches the game.
cd "$REPO_ROOT"
exec ./scripts/launch-ed.sh "\$@"
EOF
chmod +x "$COMMAND_FILE"
ok "installed: $COMMAND_FILE"
ok "double-click it from Finder / ~/Applications to launch ED"

# macOS sometimes flags newly-written .command files with a quarantine
# attribute which throws a Gatekeeper warning on double-click. Strip it.
xattr -d com.apple.quarantine "$COMMAND_FILE" 2>/dev/null || true
